server:
  port: 8080

spring:
  redis:
    host: localhost
    port: 6379
    database: 1
    password:

jusic:
  music-expire-time: 1200000
  retry-count: 3
  vote-rate: 0.3
  default-music-file: file:music/default-list.txt
  music-serve-domain: 'http://domain'


