server:
  port: 8080

spring:
  redis:
    host: localhost
    port: 6379
    database: 1
    password:
  mail:
    host:
    port:
    username:
    password:
    default-encoding:

jusic:
  music-expire-time: 1200000
  retry-count: 3
  vote-rate: 0.3
  default-music-file: file:music/default-list.txt
  playlist-id: 3778678
  music-serve-domain: 'http://domain'
  mail-send-from: 'xx@email.com'
  mail-send-to: 'xx@email.com'

